# Generated by Django 3.0.4 on 2020-03-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('alignment', models.CharField(choices=[('h', 'hero'), ('v', 'villain')], max_length=1)),
                ('weakness', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('nemeses', models.ManyToManyField(related_name='_user_nemeses_+', to='Daemon.User')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headquarters', models.CharField(max_length=100)),
                ('inception', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=250)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='Daemon.User')),
                ('members', models.ManyToManyField(related_name='team', to='Daemon.User')),
            ],
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('users', models.ManyToManyField(related_name='powers', to='Daemon.User')),
            ],
        ),
    ]
